using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// This class is responsible for calcting points that form a rectangle along the surface generated by RectangleToRaycast script
/// </summary>
public class RaycastToRectangle : MonoBehaviour
{
    public RectangleToRayCast rectangleToRayCast;
    /// <summary>The Transform component reference of Bone Weight Bottom Left Back</summary>
    public Transform bottomLeftBackAligned;
    /// <summary>The Transform component reference of Bone Weight Bottom Left Back</summary>
    public Transform topLeftBackAligned;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        // calculate the distance between the front two points

        // calculate the middle points of the back line

        // generate points 




        // find points on back line by doing Vector3.Forward
        // find 
    }
}
